echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "I am learning branching in git and github"
echo "Proud of you batch-33"
echo "Our new batch will start on 4th Oct"
echo "i am devops enginner"
echo "I got 20 lpa package" 
echo "Our new batch will start from 8 october"
echo "I will be availavle at hinjewadi office on sunday"
echo "Today I am learning merged conflicts"
echo "Good Morning"

